
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jhon
 */
public class NewJFrame extends javax.swing.JFrame {
    ArrayList<Nuotatore> nuotatori=new ArrayList<>();
    ArrayList<Pallavolista> pallavolisti=new ArrayList<>();
    DefaultTableModel dtm=new DefaultTableModel(new Object[][]{},new Object[]{"Nome","Nazionalita'","Numero Gare","Anno Nascita","Stile","Tempo 100m","Tempo 200m","Falli","Partite Vinte","Partite Perse"});
    DefaultComboBoxModel dcbm=new DefaultComboBoxModel();
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        jTable1.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnins = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtarea = new javax.swing.JTextArea();
        txtnuot = new javax.swing.JTextField();
        btnnuot = new javax.swing.JButton();
        txtpall = new javax.swing.JTextField();
        btnpall = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cbxnaz = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnins.setText("Inserisci");
        btnins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninsActionPerformed(evt);
            }
        });

        txtarea.setColumns(20);
        txtarea.setRows(5);
        jScrollPane1.setViewportView(txtarea);

        txtnuot.setText("jTextField1");

        btnnuot.setText("Cerca");
        btnnuot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuotActionPerformed(evt);
            }
        });

        txtpall.setText("jTextField1");

        btnpall.setText("Cerca");
        btnpall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpallActionPerformed(evt);
            }
        });

        jButton1.setText("Scarto minore V/P");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("eta' media");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        cbxnaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxnazActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtnuot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnnuot))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtpall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpall))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(btnins))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxnaz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(btnins)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jButton1)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtnuot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnnuot))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtpall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnpall))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jButton2)))
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(cbxnaz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btninsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsActionPerformed
        String nome=JOptionPane.showInputDialog("Inserisci il nome dell'atleta");
        String nazionalita=JOptionPane.showInputDialog("Inserisci la nazionalita'");
        int numeroGare=Integer.valueOf(JOptionPane.showInputDialog("Inserisci il numero di gare"));
        int annoNascita=Integer.valueOf(JOptionPane.showInputDialog("Inserisci l'anno di nascita"));
        Object[] opzioni = {"Nuotatore", "Pallavolista"};
        Object selezione = JOptionPane.showInputDialog(null, "Seleziona il tipo di atleta:", "Tipo", JOptionPane.INFORMATION_MESSAGE, null, opzioni, opzioni[0]);
        if(selezione.equals("Nuotatore")){
            String stile=JOptionPane.showInputDialog("Inserisci lo stile preferito");
            int tempo100=Integer.valueOf(JOptionPane.showInputDialog("Inserisci il tempo record sui 100 metri in secondi"));
            int tempo200=Integer.valueOf(JOptionPane.showInputDialog("Inserisci il tempo record sui 100 metri in secondi"));
            Nuotatore nuotatore=new Nuotatore(stile, tempo100, tempo200, nome, nazionalita, numeroGare, annoNascita);
            nuotatori.add(nuotatore);
        }else{
            int falli=Integer.valueOf(JOptionPane.showInputDialog("Inserisci il numero di falli"));
            int vinte=Integer.valueOf(JOptionPane.showInputDialog("Inserisci il numero di partite vinte"));
            int perse=Integer.valueOf(JOptionPane.showInputDialog("Inserisci il numero di partite perse"));
            Pallavolista pallavolista=new Pallavolista(falli, vinte, perse, nome, nazionalita, numeroGare, annoNascita);
            Object[] row={nome,nazionalita,numeroGare,annoNascita,"/","/","/",falli,vinte,perse};
            dtm.addRow(row);
            pallavolisti.add(pallavolista);
        }
        for(int i=0;i<dcbm.getSize();i++){
            if(!dcbm.getElementAt(i).toString().equals(nazionalita)) {
                dcbm.addElement(nazionalita);
            }
        }
    }//GEN-LAST:event_btninsActionPerformed

    private void btnnuotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuotActionPerformed
        for(int i=0;i<nuotatori.size();i++){
            if(txtnuot.equals(nuotatori.get(i).nome)){
                txtarea.setText(nuotatori.get(i).tostring());
            }
        }
    }//GEN-LAST:event_btnnuotActionPerformed

    private void btnpallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpallActionPerformed
        for(int i=0;i<pallavolisti.size();i++){
            if(txtpall.equals(pallavolisti.get(i).nome)){
                txtarea.setText(pallavolisti.get(i).toString());
            }
        }
    }//GEN-LAST:event_btnpallActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int pos=0;
        int scarto=pallavolisti.getFirst().vinte-pallavolisti.getFirst().perse;
        for(int i=0;i<pallavolisti.size();i++){
            if((pallavolisti.get(i).vinte-pallavolisti.get(i).perse)<scarto){
                pos=i;
                scarto=pallavolisti.get(i).vinte-pallavolisti.get(i).perse;
            }
        }
        txtarea.setText("Lo scarto minore tra partite vine e partite perse ce l'ha "+pallavolisti.get(pos).nome+"\n"+pallavolisti.get(pos).toString());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int num=0,s=0;
        for(int i=0;i<nuotatori.size();i++){
            s+=nuotatori.get(i).eta(nuotatori.get(i).annoNascita);
            num++;
        }
        for(int i=0;i<pallavolisti.size();i++){
            s+=pallavolisti.get(i).eta(pallavolisti.get(i).annoNascita);
            num++;
        }
        txtarea.setText("l'eta' media tra nuotatori e pallavolisti e': "+(s/num));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbxnazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxnazActionPerformed
        String naz=cbxnaz.getSelectedItem().toString();
        dtm.setNumRows(0);
        for(int i=0;i<nuotatori.size();i++){
            if(nuotatori.get(i).nazionalita.equals(naz.toUpperCase(Locale.ITALY))
        Object[] row={nuotatori.get(i).nome,nuotatori.get(i).nazionalita,nuotatori.get(i).numeroGare,nuotatori.get(i).annoNascita,nuotatori.get(i).stile,nuotatori.get(i).tempo100,nuotatori.get(i).tempo200,"/","/","/"};
        dtm.addRow(row);
            
        }
    }//GEN-LAST:event_cbxnazActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnins;
    private javax.swing.JButton btnnuot;
    private javax.swing.JButton btnpall;
    private javax.swing.JComboBox<String> cbxnaz;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea txtarea;
    private javax.swing.JTextField txtnuot;
    private javax.swing.JTextField txtpall;
    // End of variables declaration//GEN-END:variables
}
