/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jhon
 */
public class Finestra extends javax.swing.JFrame {

    /**
     * Creates new form Finestra
     */
    public Finestra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtint = new javax.swing.JLabel();
        chx120 = new javax.swing.JCheckBox();
        chx15 = new javax.swing.JCheckBox();
        chx289 = new javax.swing.JCheckBox();
        chx102 = new javax.swing.JCheckBox();
        chx39 = new javax.swing.JCheckBox();
        btntot = new javax.swing.JButton();
        txttot = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtint.setText("Elenco merci da spedire");

        chx120.setText("Stampante HP (120€)");
        chx120.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chx120ActionPerformed(evt);
            }
        });

        chx15.setText("Mouse Logitech (15€)");
        chx15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chx15ActionPerformed(evt);
            }
        });

        chx289.setText("Stampante Epson (289€)");
        chx289.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chx289ActionPerformed(evt);
            }
        });

        chx102.setText("Scanner Orion (102€)");
        chx102.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chx102ActionPerformed(evt);
            }
        });

        chx39.setText("PenLight MicroChannel (39€)");
        chx39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chx39ActionPerformed(evt);
            }
        });

        btntot.setText("TOTALE");
        btntot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntotActionPerformed(evt);
            }
        });

        txttot.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btntot)
                        .addGap(18, 18, 18)
                        .addComponent(txttot, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chx39)
                    .addComponent(chx102)
                    .addComponent(chx289)
                    .addComponent(chx15)
                    .addComponent(chx120)
                    .addComponent(txtint))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(txtint)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chx120)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chx15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chx289)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chx102)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chx39)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntot)
                    .addComponent(txttot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chx120ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chx120ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chx120ActionPerformed

    private void chx15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chx15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chx15ActionPerformed

    private void chx289ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chx289ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chx289ActionPerformed

    private void chx102ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chx102ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chx102ActionPerformed

    private void chx39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chx39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chx39ActionPerformed

    private void btntotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntotActionPerformed
        int s=0;
        if(chx102.isSelected())
            s+=102;
        if(chx120.isSelected())
            s+=120;
        if(chx15.isSelected())
            s+=15;
        if(chx289.isSelected())
            s+=289;
        if(chx39.isSelected())
            s+=39;
        txttot.setText(String.valueOf(s));
    }//GEN-LAST:event_btntotActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Finestra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btntot;
    private javax.swing.JCheckBox chx102;
    private javax.swing.JCheckBox chx120;
    private javax.swing.JCheckBox chx15;
    private javax.swing.JCheckBox chx289;
    private javax.swing.JCheckBox chx39;
    private javax.swing.JLabel txtint;
    private javax.swing.JTextField txttot;
    // End of variables declaration//GEN-END:variables
}
