
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 * @author La Porta Luca Maria
 * @version 03/02/2024
 */
public class PannelloViaggio extends javax.swing.JFrame { 
    
    /**
     * Creates new form PannelloViaggio
     */
    public PannelloViaggio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        lblViaggiatori = new javax.swing.JLabel();
        lblBambini = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblDurata = new javax.swing.JLabel();
        lblAereo = new javax.swing.JLabel();
        lblCitta = new javax.swing.JLabel();
        lblDestinazione = new javax.swing.JLabel();
        lblAuto = new javax.swing.JLabel();
        lblPrezzo = new javax.swing.JLabel();
        cmbxBambini = new javax.swing.JComboBox<>();
        cmbxViaggiatori = new javax.swing.JComboBox<>();
        txtDestinazione = new javax.swing.JTextField();
        rbtnAereoSI = new javax.swing.JRadioButton();
        rbtnAereoNO = new javax.swing.JRadioButton();
        txtCitta = new javax.swing.JTextField();
        rbtnAutoSI = new javax.swing.JRadioButton();
        rbtnAutoNO = new javax.swing.JRadioButton();
        cmbxPrezzo = new javax.swing.JComboBox<>();
        btnInserisci = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        Calendar1 = new com.toedter.calendar.JDateChooser();
        Calendar2 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ORGANIZZA VIAGGIO");
        setResizable(false);

        lblViaggiatori.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        lblViaggiatori.setText("NUMERO VIAGGIATORI");

        lblBambini.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        lblBambini.setText("NUMERO BAMBINI (1-16 anni)");

        lblData.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        lblData.setText("INSERIRE DATA DI PARTENZA");

        lblDurata.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        lblDurata.setText("INSERIRE DATA RITORNO");

        lblAereo.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        lblAereo.setText("VIAGGIO IN AEREO");

        lblCitta.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        lblCitta.setText("CITTA' DI PARTENZA");

        lblDestinazione.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        lblDestinazione.setText("SCEGLI DESTINAZIONE");

        lblAuto.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        lblAuto.setText("NOLEGGIO AUTO");

        lblPrezzo.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        lblPrezzo.setText("FASCIA DI PREZZO");

        cmbxBambini.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        cmbxBambini.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        cmbxViaggiatori.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        cmbxViaggiatori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        txtDestinazione.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N

        buttonGroup1.add(rbtnAereoSI);
        rbtnAereoSI.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        rbtnAereoSI.setText("SI");

        buttonGroup1.add(rbtnAereoNO);
        rbtnAereoNO.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        rbtnAereoNO.setText("NO");

        txtCitta.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N

        buttonGroup2.add(rbtnAutoSI);
        rbtnAutoSI.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        rbtnAutoSI.setText("SI");

        buttonGroup2.add(rbtnAutoNO);
        rbtnAutoNO.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        rbtnAutoNO.setText("NO");

        cmbxPrezzo.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        cmbxPrezzo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "50-100", "100-200", "200-500", "500-1000", "1000-1500", "1500+" }));

        btnInserisci.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        btnInserisci.setText("INSERISCI DATI");
        btnInserisci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserisciActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        Calendar1.setDateFormatString("dd MM yyyy");

        Calendar2.setDateFormatString("dd MM yyyy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblViaggiatori)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(cmbxViaggiatori, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(rbtnAereoSI)
                                            .addGap(18, 18, 18)
                                            .addComponent(rbtnAereoNO))
                                        .addComponent(lblAereo))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCitta)
                                    .addComponent(txtCitta, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(rbtnAutoSI)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtnAutoNO))
                            .addComponent(lblAuto)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(cmbxBambini, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblBambini)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Calendar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblData, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(btnInserisci, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addComponent(lblDurata)
                    .addComponent(lblDestinazione)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPrezzo)
                            .addComponent(Calendar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbxPrezzo, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txtDestinazione, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDestinazione)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDestinazione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDurata)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Calendar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblPrezzo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbxPrezzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblViaggiatori)
                            .addComponent(lblBambini))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbxBambini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbxViaggiatori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblCitta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCitta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblAereo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rbtnAereoSI)
                                    .addComponent(rbtnAereoNO))
                                .addGap(47, 47, 47))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblData)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Calendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(lblAuto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rbtnAutoSI)
                                    .addComponent(rbtnAutoNO))
                                .addGap(42, 42, 42)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnReset)
                            .addComponent(btnInserisci))
                        .addGap(35, 35, 35))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInserisciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserisciActionPerformed
        String stampa = "HAI SCELTO: \n";       
        String viaggiatori = (String) cmbxViaggiatori.getSelectedItem();
        stampa += "Numero Viaggiatori: "+viaggiatori+"\n";
        
        String bambini = (String) cmbxBambini.getSelectedItem();
        stampa += "Numero Bambini: "+bambini+"\n";
        
        String destinazione = txtDestinazione.getText();
        stampa += "Destinazione: "+destinazione+"\n";

        String dataPart = ((JTextField)Calendar1.getDateEditor().getUiComponent()).getText();
        stampa += "Data di Partenza: "+dataPart+"\n";
        
        String dataRit = ((JTextField)Calendar2.getDateEditor().getUiComponent()).getText();
        stampa += "Data di Ritorno: "+dataRit+"\n";

        if(rbtnAereoSI.isSelected()){
           stampa += "Viaggio in aereo: SI \n";
        }else{
            stampa += "Viaggio in aereo: NO \n";
        }           
        
        if(rbtnAutoSI.isSelected()){
            stampa += "Viaggio in auto: SI \n";
        }else{
            stampa += "Viaggio in auto: NO \n";
        }
        
        String partenza = txtCitta.getText();
        stampa += "Partenza: "+partenza+"\n";
                
        String prezzo = (String) cmbxPrezzo.getSelectedItem();
        stampa += "Fascia Prezzo: "+prezzo+"\n";   
        
        JOptionPane.showMessageDialog(null, stampa);
    }//GEN-LAST:event_btnInserisciActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
       txtDestinazione.setText("");
       txtCitta.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PannelloViaggio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PannelloViaggio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PannelloViaggio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PannelloViaggio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PannelloViaggio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Calendar1;
    private com.toedter.calendar.JDateChooser Calendar2;
    private javax.swing.JButton btnInserisci;
    private javax.swing.JButton btnReset;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cmbxBambini;
    private javax.swing.JComboBox<String> cmbxPrezzo;
    private javax.swing.JComboBox<String> cmbxViaggiatori;
    private javax.swing.JLabel lblAereo;
    private javax.swing.JLabel lblAuto;
    private javax.swing.JLabel lblBambini;
    private javax.swing.JLabel lblCitta;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblDestinazione;
    private javax.swing.JLabel lblDurata;
    private javax.swing.JLabel lblPrezzo;
    private javax.swing.JLabel lblViaggiatori;
    private javax.swing.JRadioButton rbtnAereoNO;
    private javax.swing.JRadioButton rbtnAereoSI;
    private javax.swing.JRadioButton rbtnAutoNO;
    private javax.swing.JRadioButton rbtnAutoSI;
    private javax.swing.JTextField txtCitta;
    private javax.swing.JTextField txtDestinazione;
    // End of variables declaration//GEN-END:variables
}
