
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author giann
 */
public class NewJFrame1 extends javax.swing.JFrame {
    ArrayList<Biblioteca> biblioteche=new ArrayList<>();
    DefaultComboBoxModel<String> comboBoxModel=new DefaultComboBoxModel<>();
    /**
     * Creates new form NewJFrame1
     */
    public NewJFrame1() {
        initComponents();
        comboBoxModel=new DefaultComboBoxModel<>();
        cbxbiblib.setModel(aggmodel());
    }
    
    public DefaultComboBoxModel aggmodel(){
        DefaultComboBoxModel<String> comboBoxModel=new DefaultComboBoxModel<>();
        comboBoxModel.removeAllElements();
        for(int i=0;i<biblioteche.size();i++){
            comboBoxModel.addElement(biblioteche.get(i).getNome());
        }
        return comboBoxModel;
    }
    
    public void setBiblioteche(ArrayList<Biblioteca> biblioteche) {
        this.biblioteche = biblioteche;
    }

    public void setComboBoxModel(DefaultComboBoxModel<String> comboBoxModel) {
        this.comboBoxModel = comboBoxModel;
        this.cbxbiblib.setModel(comboBoxModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnlib = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtautlib = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtcelib = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtnslib = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtqtlib = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbxbiblib = new javax.swing.JComboBox<>();
        btninslib = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtprzlib = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtcodlib = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inserimento Libro");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Inserisci libro"));

        jLabel1.setText("Nome:");

        txtnlib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnlibActionPerformed(evt);
            }
        });

        jLabel2.setText("Autore");

        jLabel3.setText("Casa Editrice");

        jLabel4.setText("Numero Scaffale");

        jLabel5.setText("Quantità");

        jLabel6.setText("Biblioteca");

        cbxbiblib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxbiblibActionPerformed(evt);
            }
        });

        btninslib.setText("Inserisci");
        btninslib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninslibActionPerformed(evt);
            }
        });

        jLabel7.setText("Prezzo");

        jLabel8.setText("Codice");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtautlib, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtcelib, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel8))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnlib)
                            .addComponent(txtcodlib)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxbiblib, 0, 143, Short.MAX_VALUE)
                            .addComponent(txtnslib)
                            .addComponent(txtqtlib, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtprzlib))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(btninslib)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtnlib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtcodlib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtautlib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtcelib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtprzlib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtnslib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtqtlib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbxbiblib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btninslib)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btninslibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninslibActionPerformed
        int num=0;
        Biblioteca selbib=new Biblioteca("", "", "");
        String nome=txtnlib.getText();
        int codice=Integer.valueOf(txtcodlib.getText());
        String autore=txtautlib.getText();
        String casaed=txtcelib.getText();
        float prz=Float.valueOf(txtprzlib.getText());
        int nscaff=Integer.valueOf(txtnslib.getText());
        int quantita=Integer.valueOf(txtqtlib.getText());
        String stringbiblioteca=cbxbiblib.getSelectedItem().toString();
        for(int i=0;i<biblioteche.size();i++){
            if(stringbiblioteca.equals(biblioteche.get(i).getNome())){
                selbib=biblioteche.get(i);
                num=i;
            }
        }
        Libro libro=new Libro(nome, codice, autore, casaed, prz, nscaff, quantita, selbib);
        selbib.addlib(libro);
        biblioteche.set(num, selbib);
        txtautlib.setText("");
        txtcelib.setText("");
        txtcodlib.setText("");
        txtnlib.setText("");
        txtnslib.setText("");
        txtprzlib.setText("");
        txtqtlib.setText("");
        NewJFrame frame=new NewJFrame();
        frame.setTxtlog("Libro Inserito correttamente");
        NewJFrame1 frame1=new NewJFrame1();
        frame1.setVisible(false);
    }//GEN-LAST:event_btninslibActionPerformed

    private void txtnlibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnlibActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnlibActionPerformed

    private void cbxbiblibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxbiblibActionPerformed
    }//GEN-LAST:event_cbxbiblibActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewJFrame1 frame=new NewJFrame1();
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btninslib;
    private javax.swing.JComboBox<String> cbxbiblib;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtautlib;
    private javax.swing.JTextField txtcelib;
    private javax.swing.JTextField txtcodlib;
    private javax.swing.JTextField txtnlib;
    private javax.swing.JTextField txtnslib;
    private javax.swing.JTextField txtprzlib;
    private javax.swing.JTextField txtqtlib;
    // End of variables declaration//GEN-END:variables
}
