
import javax.swing.JButton;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jhon
 */
public class Finestra extends javax.swing.JFrame {

    /**
     * Creates new form Finestra
     */
    public Finestra() {
        initComponents();
    }

    float prz,tot;
    int q,i=0;
    public float getprz(){
        return prz;
    }
    
    public int getq(){
        return q;
    }

    public float gettot() {
        return tot;
    }

    public int geti() {
        return i;
    }
    
    public void setprz(float nuovo){
        this.prz=nuovo;
    }

    public void setq(int nuovo) {
        this.q = nuovo;
    }

    public void settot(float nuovo) {
        this.tot = nuovo;
    }

    public void seti(int nuovo) {
        this.i = nuovo;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prztxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        qtxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tottxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mprzbtn = new javax.swing.JButton();
        mqbtn = new javax.swing.JButton();
        totbtn = new javax.swing.JButton();
        aggbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        prztxt.setText("jTextField1");

        jLabel1.setText("Prezzo");

        qtxt.setText("jTextField2");

        jLabel2.setText("Quantità");

        tottxt.setText("jTextField3");

        jLabel3.setText("Importo parziale");

        mprzbtn.setText("Media Prezzo");
        mprzbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mprzbtnActionPerformed(evt);
            }
        });

        mqbtn.setText("Media Quantità");
        mqbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mqbtnActionPerformed(evt);
            }
        });

        totbtn.setText("Tot Vendite");
        totbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totbtnActionPerformed(evt);
            }
        });

        aggbtn.setText("Aggiungi");
        aggbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(52, 52, 52))
                    .addComponent(prztxt)
                    .addComponent(mprzbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(40, 40, 40))
                    .addComponent(qtxt)
                    .addComponent(mqbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tottxt)
                    .addComponent(totbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aggbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prztxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tottxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mprzbtn)
                    .addComponent(mqbtn)
                    .addComponent(totbtn))
                .addGap(45, 45, 45)
                .addComponent(aggbtn)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aggbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggbtnActionPerformed
        int q;
        float prz,tot;
        setprz(Float.valueOf(prztxt.getText())+getprz());
        setq(Integer.valueOf(qtxt.getText())+getq());
        settot(Float.valueOf(tottxt.getText())+gettot());
        int i=geti();
        i++;
        seti(i);
        
    }//GEN-LAST:event_aggbtnActionPerformed

    private void mprzbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mprzbtnActionPerformed
        float mprz=getprz()/geti();
        prztxt.setText(String.valueOf(mprz));
    }//GEN-LAST:event_mprzbtnActionPerformed

    private void mqbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mqbtnActionPerformed
        int mq=getq()/geti();
        qtxt.setText(String.valueOf(mq));
    }//GEN-LAST:event_mqbtnActionPerformed

    private void totbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totbtnActionPerformed
        tottxt.setText(String.valueOf(gettot()));
    }//GEN-LAST:event_totbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Finestra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aggbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton mprzbtn;
    private javax.swing.JButton mqbtn;
    private javax.swing.JTextField prztxt;
    private javax.swing.JTextField qtxt;
    private javax.swing.JButton totbtn;
    private javax.swing.JTextField tottxt;
    // End of variables declaration//GEN-END:variables
}
